Fix class method has no attribute '__name__' error
when I passed a class method to async_task like:

```python3
async_task(instance.fetch_issues, task_name=f'fetch_issues_by_version:{instance.id}')
```
I got error like below:
 ERROR | cluster.py:521 | 'Release' object has no attribute '__name__'

the root cause is that a python class instance has no attribute __name__, it stored in __dict__, if you want to get the class name, you have to called like below:

```python3
method.__self__.__class__.__name__
```
works in python-3.9.4
refer: https://stackoverflow.com/questions/14514838/why-do-python-instances-have-no-name-attribute